import Head from 'next/head'
import Image from 'next/image'
import { Post } from '@/types'





type Props = {
  data: Post[]
}


export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3001/api/v1/posts')
  const data = await res.json()
  console.log(data);
  
  return {
    props: {
      data,
    }
  }
}



export default function Home({data}: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data.map((post) => (
          <div key={post.id}>
            <h2>{post.title}</h2>
            <p>{post.category}</p>
            <p>{post.income}</p>
          </div>
        ))}
      </div>
      
    </>
  )
}
